[versions]
agp = "8.13.0"
kotlin = "2.2.0"
core-ktx = "1.12.0"
junit = "4.13.2"
junit-ext = "1.1.5"
espresso-core = "3.5.1"
activity-compose = "1.11.0"
appcompat = "1.7.1"
lifecycle-runtime-ktx = "2.9.4"
material = "1.13.0"
material3 = "1.4.0"
ui = "1.9.4"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit-ext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }